# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [test, lint, format, coverage]
    name: ${{ matrix.task }}
    env:
      # Variables de entorno necesarias para testing
      DATABASE_URL: "file:./test.db"
      NEXTAUTH_SECRET: "test-secret-for-ci"
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "test"
      # Variables para AWS S3 (valores dummy para testing)
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_S3_BUCKET_NAME: "test-bucket"
      # Variables para autenticación
      AUTH_SESSION_COOKIE_NAME: "better-auth-session-token"
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile     

      - name: Generate Prisma Client
        run: |
          echo "Generating Prisma client..."
          pnpm prisma generate
          echo "Prisma client generated successfully"

      - if: matrix.task == 'format'
        name: Install Biome
        run: pnpm add -g @biomejs/biome

      - name: Run ${{ matrix.task }}
        run: |
          case "${{ matrix.task }}" in
            verify)
              pnpm run verify:aliases
              ;;
            test)
              pnpm run test
              ;;
            lint)
              pnpm run lint
              ;;
            format)
              pnpm run format
              ;;
            coverage)
              pnpm run test:coverage
              ;;
          esac

      - if: matrix.task == 'coverage'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
