# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [test, lint, format, coverage]
    name: ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile     

      - if: matrix.task == 'format'
        name: Install Biome
        run: pnpm add -g @biomejs/biome

      - name: Run ${{ matrix.task }}
        run: |
          case "${{ matrix.task }}" in
            verify)
              pnpm run verify:aliases
              ;;
            test)
              pnpm run test
              ;;
            lint)
              pnpm run lint
              ;;
            format)
              pnpm run format
              ;;
            coverage)
              pnpm run test:coverage
              ;;
          esac

      - if: matrix.task == 'coverage'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
