# .github/workflows/ci.yml
name: CI

on:
  push:         { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [test, lint, format, coverage]   # <- lo que antes eran 4 jobs
    name: ${{ matrix.task }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4           # primero pnpm
        with:
          version: 8
          run_install: false                 # evitá doble install

      - uses: actions/setup-node@v4          # ahora Node + cache
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - run: pnpm install --no-frozen-lockfile  # crea el store

      - name: Run ${{ matrix.task }}
        run: |
          case "${{ matrix.task }}" in
            test) pnpm test ;;
            lint) pnpm lint ;;
            format) pnpm format ;;
            coverage) pnpm test:coverage ;;
          esac

      - if: matrix.task == 'coverage'        # subí el reporte
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
