name: Pull Request Validation

on:
  pull_request:
    branches: ["main", "master"]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const jobUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            
            let emoji = "";
            let status = "";
            if (context.job.status === "success") {
              emoji = "✅";
              status = "El PR pasó todas las validaciones! 🎉";
            } else {
              emoji = "❌";
              status = "Hay validaciones que fallaron. Por favor revisa los detalles.";
            }
            
            const comment = `
            # Resultado de Validación ${emoji}
            
            ${status}
            
            Ver detalles completos [aquí](${jobUrl}).
            `;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            }); 