name: Test Coverage

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  # Permitir ejecutar manualmente el workflow desde la interfaz de GitHub
  workflow_dispatch:

jobs:
  test-coverage:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        run: pnpm test:coverage

      # Opcional: Guardar el reporte de cobertura como artefacto
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

      # Opcional: Comentar el resultado de la cobertura en PRs (requiere configuración adicional)
      # - name: Comment coverage on PR
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: true
      #     directory: ./coverage
      #     verbose: true 